Repository FormidableLabs/enzyme-matchers, pull requests merged in 2018-03, with the labels that each got.

#213 Allow propKey to be an Object
  packages/enzyme-matchers/src/assertions/toHaveProp.js
Labels: V - PATCH

#216 Better linting file support
  packages/eslint-config-jest-enzyme/index.js
Labels: Bug - EslintConfigJestEnzyme, V - PATCH

#224 Fix requiring adapter for peerDependency
  package.json
  packages/jest-environment-enzyme/package.json
  packages/jest-environment-enzyme/src/setup.js
  yarn.lock
Labels: V - MAJOR

#225 Cleanup jasmine-enzyme failure message
  packages/jasmine-enzyme/src/index.js
Labels: Bug - JasmineEnzyme, V - PATCH
